package net.lyx.dbframework.testengine.dao.entity;

import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.lyx.dbframework.dao.entity.EntityAccessible;
import net.lyx.dbframework.dao.entity.EntityAutoGenerated;
import net.lyx.dbframework.dao.entity.EntityElement;

@Builder
@ToString
@EqualsAndHashCode
@EntityAccessible(name = "Users")
public class User {

    @EntityAutoGenerated
    private long id;

    @EntityElement(order = 3)
    private String lastName;

    @EntityElement(order = 2)
    private String firstName;

    @EntityElement(order = 4)
    private Status status;
}
